name: Test Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v2
      - name: Run Automated Tests
        working-directory: ${{ github.workspace }}/testing
        run: ${{ github.workspace }}/testing/test
