name: Test Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repository Code
        uses: actions/checkout@v2
      - name: Change To Testing Directory
        run: cd ${{ github.workspace }}/testing
      - name: Run Automated Tests
        run: ${{ github.workspace }}/testing/test
