name: Test Integration
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Print Date
        run: date
      - name: Check Out Repository Code
        uses: actions/checkout@v2
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: 3.10.2
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run Automated Tests
        working-directory: ${{ github.workspace }}/testing
        run: ${{ github.workspace }}/testing/test
      - name: Upload Test Results
        if: always()
        uses: actions/upload-artifact@v1
        with:
          name: test-results
          path: testing/test.log
